#!/usr/bin/env perl
use Mojolicious::Lite;
get '/' => sub { 
	shift->render('hello'); 
};

get '/:fname/:lname' => sub {
	my $self = shift;
	$self->stash(
		fname => uc $self->param('fname'),
		lname => uc $self->param('lname')
:	);
	$self->render('capture');
};

app->start;
__DATA__
@@ hello.html.ep
Welcome to Mojolicious!!!

@@ layouts/wrapper.html.ep
<h1><%= title %></h1>

<%= content %> To Flying machine!!

@@ capture.html.ep
% title 'Planet Express';
% layout 'wrapper';

Hello <%= $fname %> <%= $lname %>!!






